/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import { Loader2, Pencil, Trash2, Save, X, BadgeCheck, IndianRupee } from "lucide-react";
import API from "../../api/axios";

const empty = { packageName:"", category:"Routine", description:"", testsIncluded:"", price:"", turnaroundTime:"24-48 hours", sampleType:"Blood / Urine / Sample", isPopular:false };
const LabPackages = () => {
  const [packages,setPackages]=useState([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
  const load=async()=>{try{setLoading(true);const r=await API.get("/labs/packages/my");setPackages(r.data.packages||[]);}catch(e){setError(e.response?.data?.message||"Failed to load packages");}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const change=e=>{const {name,value,type,checked}=e.target;setForm(p=>({...p,[name]:type==="checkbox"?checked:value}));};
  const submit=async e=>{e.preventDefault();setError("");setSuccess("");if(!form.packageName.trim()||form.price===""){setError("Package name and price are required.");return;}try{setSaving(true);const payload={...form,price:Number(form.price),testsIncluded:form.testsIncluded.split(",").map(x=>x.trim()).filter(Boolean)};if(editing)await API.patch(`/labs/packages/${editing}`,payload);else await API.post("/labs/packages",payload);setSuccess(editing?"Package updated successfully.":"Package created successfully.");setForm(empty);setEditing(null);await load();}catch(e){setError(e.response?.data?.message||"Unable to save package");}finally{setSaving(false);}};
  const edit=item=>{setEditing(item._id);setForm({...empty,...item,testsIncluded:(item.testsIncluded||[]).join(", ")});window.scrollTo({top:0,behavior:"smooth"});};
  const setPackageActive=async(id,isActive)=>{if(!window.confirm(isActive?"Reactivate this package?":"Archive this package?"))return;try{await API.patch(`/labs/packages/${id}`,{isActive});setSuccess(isActive?"Package reactivated.":"Package archived.");await load();}catch(e){setError(e.response?.data?.message||"Unable to update package");}};
  if(loading)return <Loader />;
  return <div className="space-y-8"><header className="overflow-hidden rounded-[2rem] bg-gradient-to-r from-cyan-600 to-emerald-500 p-6 text-white shadow-xl shadow-cyan-100"><div className="inline-flex items-center gap-2 rounded-full bg-white/20 px-4 py-2 text-sm font-bold"><BadgeCheck size={18}/>Vendor Package Catalog</div><h1 className="mt-3 text-3xl font-black">Manage Test Packages</h1><p className="mt-2 max-w-2xl text-sm text-cyan-50">Publish clear diagnostic packages that patients can discover and book.</p></header>
  {error&&<Notice tone="red">{error}</Notice>}{success&&<Notice tone="green">{success}</Notice>}
  <div className="grid gap-6 lg:grid-cols-[1fr_1fr]"><form onSubmit={submit} className="rounded-[1.5rem] border border-white/70 bg-white/90 p-6 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-black text-slate-900">{editing?"Edit package":"Create package"}</h2><p className="text-sm text-slate-500">All fields remain under your lab ownership.</p></div>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty);}} className="rounded-xl p-2 text-slate-500 hover:bg-slate-100"><X/></button>}</div><div className="grid gap-5 md:grid-cols-2">{[["packageName","Package name","text","Full Body Checkup"],["price","Price","number","1499"],["turnaroundTime","Turnaround time","text","24-48 hours"],["sampleType","Sample type","text","Blood / Urine / Sample"]].map(([name,label,type,ph])=><Field key={name} name={name} label={label} type={type} value={form[name]} onChange={change} placeholder={ph}/>) }<Select name="category" label="Category" value={form.category} onChange={change} options={["Basic","Premium","Routine","Advanced","Custom"]}/><div className="md:col-span-2"><Field name="testsIncluded" label="Tests included" value={form.testsIncluded} onChange={change} placeholder="CBC, LFT, KFT, Thyroid"/><p className="mt-1 text-xs text-slate-400">Separate tests with commas.</p></div><div className="md:col-span-2"><label className="mb-2 block text-sm font-bold text-slate-700">Description</label><textarea name="description" value={form.description} onChange={change} rows="4" className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:border-cyan-500"/></div><label className="md:col-span-2 inline-flex items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-bold text-slate-700"><input type="checkbox" name="isPopular" checked={form.isPopular} onChange={change}/>Mark as popular</label></div><button disabled={saving} className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-cyan-600 px-6 py-3 font-black text-white shadow-lg shadow-cyan-200 disabled:opacity-60">{saving?<Loader2 className="animate-spin" size={18}/>:<Save size={18}/>} {saving?"Saving...":editing?"Update package":"Publish package"}</button></form>
  <div className="space-y-4">{packages.length===0?<Empty text="No packages yet. Create your first package."/>:packages.map(item=><article key={item._id} className={`rounded-[1.5rem] border border-white/70 bg-white/90 p-5 shadow-sm ${!item.isActive?"opacity-60":``}`}><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-black text-slate-900">{item.packageName}</h3><span className="rounded-full bg-cyan-100 px-2 py-1 text-[10px] font-black uppercase text-cyan-700">{item.category}</span>{item.isPopular&&<span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-black uppercase text-amber-700">Popular</span>}</div><p className="mt-1 text-sm text-slate-500">{item.turnaroundTime} • {item.sampleType}</p></div><div className="inline-flex items-center gap-1 rounded-full bg-emerald-100 px-3 py-1 text-sm font-black text-emerald-700"><IndianRupee size={14}/>{item.price}</div></div><p className="mt-3 text-sm text-slate-600">{item.description||"No description added."}</p>{item.testsIncluded?.length>0&&<div className="mt-3 flex flex-wrap gap-2">{item.testsIncluded.map((t,i)=><span key={`${t}-${i}`} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-600">{t}</span>)}</div>}<div className="mt-4 flex flex-wrap justify-end gap-2"><button type="button" onClick={()=>edit(item)} className="inline-flex items-center gap-2 rounded-xl border border-cyan-200 bg-cyan-50 px-3 py-2 text-xs font-black text-cyan-700"><Pencil size={14}/>Edit</button>{item.isActive?<button type="button" onClick={()=>setPackageActive(item._id,false)} className="inline-flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs font-black text-red-600"><Trash2 size={14}/>Archive</button>:<button type="button" onClick={()=>setPackageActive(item._id,true)} className="inline-flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-700"><BadgeCheck size={14}/>Reactivate</button>}</div></article>)}</div></div></div>;
};
const Field=({name,label,type="text",value,onChange,placeholder})=><div><label className="mb-2 block text-sm font-bold text-slate-700">{label}</label><input name={name} type={type} value={value??""} onChange={onChange} placeholder={placeholder} className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:border-cyan-500"/></div>;
const Select=({name,label,value,onChange,options})=><div><label className="mb-2 block text-sm font-bold text-slate-700">{label}</label><select name={name} value={value} onChange={onChange} className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none focus:border-cyan-500">{options.map(x=><option key={x}>{x}</option>)}</select></div>;
const Notice=({tone,children})=><div className={`rounded-2xl border p-4 text-sm font-bold ${tone==="red"?"border-red-200 bg-red-50 text-red-600":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{children}</div>;
const Loader=()=> <div className="flex min-h-[50vh] items-center justify-center"><div className="flex items-center gap-3 rounded-2xl bg-white px-5 py-4 font-bold text-slate-600 shadow"><Loader2 className="animate-spin text-cyan-600"/>Loading packages...</div></div>;
const Empty=({text})=><div className="rounded-2xl border border-dashed border-slate-200 bg-white/80 p-8 text-center text-slate-500">{text}</div>;
export default LabPackages;
